const { chromium } = require('playwright');
const http = require('http');
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const root = path.resolve(__dirname, '../../../tmp/shop-filter-browser');
(async () => {
  const server = http.createServer((req, res) => { const file = req.url === '/fixture.js' ? 'fixture.js' : 'index.html'; res.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript; charset=utf-8' : 'text/html; charset=utf-8'); res.end(fs.readFileSync(path.join(root, file))); });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true });
    for (const width of [320, 600, 900, 1280]) {
      const page = await browser.newPage({ viewport: { width, height: 1000 } });
      const errors = [];
      page.on('pageerror', error => { errors.push(error.message); console.error(error.message); });
      await page.goto(`http://127.0.0.1:${server.address().port}/?workshop&failure`);
      await page.getByRole('alert').waitFor();
      const resourceRetry = page.getByRole('button', { name: 'Retry resources' });
      await resourceRetry.focus();
      assert.equal(await resourceRetry.evaluate(element => element === document.activeElement), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `workshop-error-${width}.png`), fullPage: true });
      await page.keyboard.press('Enter');
      await page.getByRole('radio', { name: 'Group', exact: true }).waitFor();
      assert.equal(await page.getByRole('alert').count(), 0);
      assert.equal(await page.evaluate(() => window.toolLoads), 2);
      assert.equal(await page.evaluate(() => window.shopLoads), 2);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `workshop-recovered-${width}.png`), fullPage: true });
      await page.getByRole('radio', { name: 'Group', exact: true }).focus();
      await page.keyboard.press('Space');
      assert.equal(await page.getByRole('button', { name: 'Add Group', exact: true }).isDisabled(), true);
      await page.getByLabel('Group name').fill('Woodshop basics');
      await page.getByRole('combobox', { name: 'Included tools' }).fill('Woodshop saw');
      await page.getByRole('option', { name: 'Woodshop saw' }).click();
      await page.getByRole('button', { name: 'Add Group', exact: true }).click();
      assert.equal(await page.locator('#outcome').textContent(), 'Saved');
      assert.deepEqual(await page.evaluate(() => ({ name: window.savedGroup.name, shopId: window.savedGroup.shopId, ids: window.savedGroup.includedToolIds })),
        { name: 'Woodshop basics', shopId: 'wood', ids: ['wood'] });
      await page.goto(`http://127.0.0.1:${server.address().port}`);
      await page.getByText('Metalshop saw', { exact: true }).waitFor();
      const shop = page.getByRole('combobox', { name: 'Shop' });
      await shop.focus();
      assert.equal(await shop.evaluate(element => element === document.activeElement), true);
      await shop.selectOption('wood');
      await page.getByText('Metalshop saw', { exact: true }).waitFor({ state: 'hidden' });
      await page.getByText('Woodshop introduction', { exact: true }).waitFor();
      assert.equal(await page.getByText('Metalshop introduction', { exact: true }).count(), 0);
      assert.equal(await page.evaluate(() => window.shopCalls.at(-1)), 'wood');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `shop-filter-${width}.png`), fullPage: true });
      await shop.selectOption('');
      await page.getByText('Metalshop saw', { exact: true }).waitFor();
      await page.goto(`http://127.0.0.1:${server.address().port}/?failure`);
      await page.getByRole('alert').waitFor();
      assert.equal(await page.getByText('Metalshop saw', { exact: true }).count(), 0);
      const retry = page.getByRole('button', { name: 'Retry tool groups' });
      await retry.focus();
      assert.equal(await retry.evaluate(element => element === document.activeElement), true);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `group-error-${width}.png`), fullPage: true });
      await page.keyboard.press('Enter');
      await page.getByText('Metalshop introduction', { exact: true }).waitFor();
      assert.equal(await page.getByRole('alert').count(), 0);
      await page.goto(`http://127.0.0.1:${server.address().port}/?roster&failure`);
      await page.getByRole('dialog', { name: 'Check Out Member on Tool' }).waitFor();
      await page.getByRole('alert').waitFor();
      assert.equal(await page.getByRole('button', { name: 'Check Out', exact: true }).isDisabled(), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `roster-error-${width}.png`), fullPage: true, animations: 'disabled' });
      await page.getByRole('button', { name: 'Retry tool groups' }).focus();
      await page.keyboard.press('Enter');
      await page.getByRole('alert').waitFor({ state: 'hidden' });
      const groupShop = page.getByRole('combobox', { name: 'Shop', exact: true });
      await groupShop.selectOption('wood');
      assert.deepEqual(await groupShop.locator('option').evaluateAll(options => options.map(option => option.value)), ['', 'wood']);
      await page.getByRole('combobox', { name: 'Tool', exact: true }).selectOption('group:wood-group');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `group-roster-${width}.png`), fullPage: true });
      await page.goto(`http://127.0.0.1:${server.address().port}/?approver&failure`);
      await page.getByRole('alert').waitFor();
      assert.equal(await page.getByRole('button', { name: 'Save Changes' }).isDisabled(), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `approver-error-${width}.png`), fullPage: true, animations: 'disabled' });
      await page.getByRole('button', { name: 'Retry tool groups' }).focus();
      await page.keyboard.press('Enter');
      await page.getByRole('button', { name: 'Woodshop introduction · Group' }).waitFor();
      await page.getByRole('button', { name: 'Save Changes' }).click();
      assert.equal(await page.locator('#outcome').textContent(), 'Saved');
      await page.goto(`http://127.0.0.1:${server.address().port}/?resolve&failure`);
      await page.getByRole('alert').waitFor();
      assert.equal(await page.getByRole('button', { name: 'Approve group', exact: true }).isDisabled(), true);
      const reviewRetry = page.getByRole('button', { name: 'Retry review' });
      await reviewRetry.focus();
      assert.equal(await reviewRetry.evaluate(element => element === document.activeElement), true);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `review-error-${width}.png`), fullPage: true });
      await page.keyboard.press('Enter');
      await page.getByRole('alert').filter({ hasText: 'Review unavailable' }).waitFor({ state: 'hidden' });
      await page.getByRole('button', { name: 'Resolve request' }).waitFor();
      await page.screenshot({ animations: 'disabled', path: path.join(root, `resolve-request-${width}.png`), fullPage: true, animations: 'disabled' });
      await page.getByRole('button', { name: 'Resolve request' }).click();
      assert.equal(await page.locator('#outcome').textContent(), 'Saved');
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.goto(`http://127.0.0.1:${server.address().port}/?catalog&failure`);
      await page.getByRole('alert').waitFor();
      await page.getByRole('button', { name: 'Retry tool groups' }).focus();
      await page.keyboard.press('Enter');
      await page.getByRole('alert').waitFor({ state: 'hidden' });
      await page.getByRole('heading', { name: 'Woodshop introduction Group' }).waitFor();
      await page.screenshot({ animations: 'disabled', path: path.join(root, `catalog-recovery-${width}.png`), fullPage: true, animations: 'disabled' });
      await page.goto(`http://127.0.0.1:${server.address().port}/?scopes`);
      await page.getByText('Group trainer', { exact: true }).waitFor();
      await page.getByText('Woodshop introduction', { exact: false }).waitFor();
      assert.equal(await page.getByRole('columnheader', { name: 'Authorized Groups' }).count(), 1);
      assert.equal(await page.getByText('Group', { exact: true }).count(), 1);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      await page.screenshot({ animations: 'disabled', path: path.join(root, `approver-scopes-${width}.png`), fullPage: true, animations: 'disabled' });
      assert.deepEqual(errors, []);
      await page.close();
      console.log(`Shop filter passed at ${width}px`);
    }
  } finally { if (browser) await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
